In [7]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

In [19]:
dfShoes = pd.read_csv("Shoes_Data.csv")

In [10]:
dfShoes.head()

title    price  \
0    CLYMB Outdoor Sports Running Shoes for Mens Boy  ₹279.00   
1              Bourge Men's Loire-z126 Running Shoes  ₹479.00   
2                               T-Rock Men's Sneaker  ₹430.00   
3  Robbie jones Sneakers Casual Canvas Fabric Col...  ₹499.00   
4                       Sparx Men's Sd0323g Sneakers  ₹499.00   

               rating  total_reviews  \
0  2.9 out of 5 stars   2389 ratings   
1  3.9 out of 5 stars  11520 ratings   
2  3.3 out of 5 stars   1251 ratings   
3  4.2 out of 5 stars      3 ratings   
4  4.2 out of 5 stars  20110 ratings   

                                 product_description  \
0  Elevate your style with this classy pair of Ru...   
1  The product will be an excellent pick for you....   
2  Flaunt with these stylish and unique red casua...   
3  Robbie Jones Shoes Are Designed To Keeping In ...   
4  Sparx is a spectacular range of footwear from ...   

                                             reviews  \
0  Not happy with product|| It's not as expected....   
1  Memory cushioning in these shoes is the best f...   
2  Worth to its amount|| Go for it|| Perfect|| 5 ...   
3  Sup quality|| Good but not expected|| Awesome 👌.!   
4  Best|| Satisfied!|| Affordable beauty 😘😘😘😘 the...   

                                      reviews_rating Shoe Type  
0  1.0 out of 5 stars|| 1.0 out of 5 stars|| 3.0 ...       Men  
1  5.0 out of 5 stars|| 1.0 out of 5 stars|| 5.0 ...       Men  
2  5.0 out of 5 stars|| 5.0 out of 5 stars|| 5.0 ...       Men  
3  5.0 out of 5 stars|| 3.0 out of 5 stars|| 5.0 ...       Men  
4  5.0 out of 5 stars|| 5.0 out of 5 stars|| 5.0 ...       Men

In [11]:
dfShoes['product_description']

0       Elevate your style with this classy pair of Ru...
1       The product will be an excellent pick for you....
2       Flaunt with these stylish and unique red casua...
3       Robbie Jones Shoes Are Designed To Keeping In ...
4       Sparx is a spectacular range of footwear from ...
                              ...                        
1225    The Nike react vision is a STORY of surreal co...
1226    The B.O.G limitless is Puma's key style for th...
1227    Lead the pack in New Balance’s Echolucent snea...
1228    Nike మహిళల రన్నింగ్ షూ ఫీల్స్ మరియు రూపం మృదువ...
1229    The GT-2000 7 achieves a reassuringly firm rid...
Name: product_description, Length: 1230, dtype: object

In [12]:
tfidf = TfidfVectorizer(stop_words="english")
dfShoes['product_description'] = dfShoes['product_description'].fillna("")
tfidf_matrix = tfidf.fit_transform(dfShoes['product_description'])

In [33]:
cosine_sim = linear_kernel(tfidf_matrix,tfidf_matrix) #I think it basically find out similaitry of each
                                                      #number with other matrix number
print(cosine_sim)

[[1.         0.         0.10983375 ... 0.00810756 0.00816093 0.02024362]
 [0.         1.         0.         ... 0.         0.         0.        ]
 [0.10983375 0.         1.         ... 0.02104758 0.00518413 0.01038312]
 ...
 [0.00810756 0.         0.02104758 ... 1.         0.01195055 0.01970824]
 [0.00816093 0.         0.00518413 ... 0.01195055 1.         0.00288827]
 [0.02024362 0.         0.01038312 ... 0.01970824 0.00288827 1.        ]]


In [14]:
dfShoes.head()['title']

0      CLYMB Outdoor Sports Running Shoes for Mens Boy
1                Bourge Men's Loire-z126 Running Shoes
2                                 T-Rock Men's Sneaker
3    Robbie jones Sneakers Casual Canvas Fabric Col...
4                         Sparx Men's Sd0323g Sneakers
Name: title, dtype: object

In [15]:
nums = pd.Series(dfShoes.index, index=dfShoes['title']).drop_duplicates()
nums #an array is created with all the shoes and its respective index

title
CLYMB Outdoor Sports Running Shoes for Mens Boy                                0
Bourge Men's Loire-z126 Running Shoes                                          1
T-Rock Men's Sneaker                                                           2
Robbie jones Sneakers Casual Canvas Fabric Colour Shoes for Men and Boys       3
Sparx Men's Sd0323g Sneakers                                                   4
                                                                            ... 
Nike Men's React Vision Running Shoes                                       1225
Puma Men's B.O.G Limitless Hi Evoknit Sneakers                              1226
new balance Women's FuelCell Echolucent Running Shoe                        1227
Nike Women's WMNS Air Zoom Pegasus 37 Running Shoe                          1228
ASICS Women Gt-2000 7 Lite-Show Running Shoes                               1229
Length: 1230, dtype: int64

In [31]:
def get_recomd(title, cosine_sim = cosine_sim):
  idx = nums[title]
  print(idx)
  sim_score = enumerate(cosine_sim[idx]) #enumeration gives us the index of the respective score
  sim_score = sorted(sim_score, key = lambda x: x[1], reverse=True) #sorting in reverse order so the most
                                                                    #matched score is printed first 
  sim_score = sim_score[1:11]
  for i in sim_score:
    print(i)
  sim_idx = [i[0] for i in sim_score]
  print(dfShoes['title'].iloc[sim_idx])

In [32]:
shoeName = str(input("Which Shoe do you want?: "))
get_recomd(shoeName)

Which Shoe do you want?: T-Rock Men's Sneaker
2
(10, 1.0)
(11, 1.0)
(27, 1.0)
(32, 1.0)
(35, 1.0)
(277, 0.7976770220339177)
(161, 0.6716478496477891)
(122, 0.6350763784446628)
(75, 0.5751653445454432)
(147, 0.37301415774199903)
10                             T-Rock Men's Sports Shoes
11              T-Rock Men's Sneaker Casual Shoes (White
27                  T-Rock Men's Navy Blue Running Shoes
32        T-Rock Socks Light Weight Sports Running Shoes
35              T-Rock Men's Casual Loafers for Men (Tan
277    D'USE Men's Stylish Running & Casual Shoes (Pa...
161    Maddy Men's Combo Pack of Shoes Sandal and Sli...
122    Maddy Running ShoesTraining ShoesGym ShoesSpor...
75                                   Clymb Men's Sneaker
147                           Sparx Men's White Sneakers
Name: title, dtype: object
